name: 'Qase Run linker'

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: false
      qase_autocomplete_run:
        description: 'Qase Run autocomplete'
        required: false
env:
  QASE_API_BASE_URL: https://api.qase.io/v1
  QASE_REPORT: 1
  QASE_RUN_ID: 5
  QASE_PROJECT_CODE: 'CPHI2'
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:

  build-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: qase-tms/qase-link-run@main

        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm ci
    
      - name: Cypress run
        uses: cypress-io/github-action@v6

     # - uses: qase-tms/qase-link-run@main

     #   env:
     #     QASE_API_TOKEN: 
          