on:
    workflow_dispatch:
      inputs:
        qase_api_base_url:
          description: 'Qase API URL'
          required: true
        qase_report:
          description: 'Enabled/disabled reporting to Qase'
          required: true
        qase_project_code:
          description: 'Qase project code'
          required: true
        qase_run_id:
          description: 'Qase Run ID'
          required: true
        qase_autocomplete_run:
          description: 'Qase Run autocomplete'
          required: true
  env:
    QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
    QASE_REPORT: ${{ inputs.qase_report }}
    QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
    QASE_RUN_ID: ${{ inputs.qase_run_id }}
    QASE_COMPLETE_RUN_AFTER_SUBMIT: ${{ inputs.qase_autocomplete_run }}
    QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}